/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.104.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Operation - Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.
type Operation struct {
	Delete *Delete
	Put *Put
	Unchanged *Unchanged
}

// DeleteAsOperation is a convenience function that returns Delete wrapped in Operation
func DeleteAsOperation(v *Delete) Operation {
	return Operation{
		Delete: v,
	}
}

// PutAsOperation is a convenience function that returns Put wrapped in Operation
func PutAsOperation(v *Put) Operation {
	return Operation{
		Put: v,
	}
}

// UnchangedAsOperation is a convenience function that returns Unchanged wrapped in Operation
func UnchangedAsOperation(v *Unchanged) Operation {
	return Operation{
		Unchanged: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Operation) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Delete
	err = newStrictDecoder(data).Decode(&dst.Delete)
	if err == nil {
		jsonDelete, _ := json.Marshal(dst.Delete)
		if string(jsonDelete) == "{}" { // empty struct
			dst.Delete = nil
		} else {
			if err = validator.Validate(dst.Delete); err != nil {
				dst.Delete = nil
			} else {
				match++
			}
		}
	} else {
		dst.Delete = nil
	}

	// try to unmarshal data into Put
	err = newStrictDecoder(data).Decode(&dst.Put)
	if err == nil {
		jsonPut, _ := json.Marshal(dst.Put)
		if string(jsonPut) == "{}" { // empty struct
			dst.Put = nil
		} else {
			if err = validator.Validate(dst.Put); err != nil {
				dst.Put = nil
			} else {
				match++
			}
		}
	} else {
		dst.Put = nil
	}

	// try to unmarshal data into Unchanged
	err = newStrictDecoder(data).Decode(&dst.Unchanged)
	if err == nil {
		jsonUnchanged, _ := json.Marshal(dst.Unchanged)
		if string(jsonUnchanged) == "{}" { // empty struct
			dst.Unchanged = nil
		} else {
			if err = validator.Validate(dst.Unchanged); err != nil {
				dst.Unchanged = nil
			} else {
				match++
			}
		}
	} else {
		dst.Unchanged = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Delete = nil
		dst.Put = nil
		dst.Unchanged = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Operation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Operation)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Operation) MarshalJSON() ([]byte, error) {
	if src.Delete != nil {
		return json.Marshal(&src.Delete)
	}

	if src.Put != nil {
		return json.Marshal(&src.Put)
	}

	if src.Unchanged != nil {
		return json.Marshal(&src.Unchanged)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Operation) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Delete != nil {
		return obj.Delete
	}

	if obj.Put != nil {
		return obj.Put
	}

	if obj.Unchanged != nil {
		return obj.Unchanged
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Operation) GetActualInstanceValue() (interface{}) {
	if obj.Delete != nil {
		return *obj.Delete
	}

	if obj.Put != nil {
		return *obj.Put
	}

	if obj.Unchanged != nil {
		return *obj.Unchanged
	}

	// all schemas are nil
	return nil
}

type NullableOperation struct {
	value *Operation
	isSet bool
}

func (v NullableOperation) Get() *Operation {
	return v.value
}

func (v *NullableOperation) Set(val *Operation) {
	v.value = val
	v.isSet = true
}

func (v NullableOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperation(val *Operation) *NullableOperation {
	return &NullableOperation{value: val, isSet: true}
}

func (v NullableOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


