/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.104.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OperationV2 - Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.
type OperationV2 struct {
	DeleteV2 *DeleteV2
	PutV2 *PutV2
	UnchangedV2 *UnchangedV2
}

// DeleteV2AsOperationV2 is a convenience function that returns DeleteV2 wrapped in OperationV2
func DeleteV2AsOperationV2(v *DeleteV2) OperationV2 {
	return OperationV2{
		DeleteV2: v,
	}
}

// PutV2AsOperationV2 is a convenience function that returns PutV2 wrapped in OperationV2
func PutV2AsOperationV2(v *PutV2) OperationV2 {
	return OperationV2{
		PutV2: v,
	}
}

// UnchangedV2AsOperationV2 is a convenience function that returns UnchangedV2 wrapped in OperationV2
func UnchangedV2AsOperationV2(v *UnchangedV2) OperationV2 {
	return OperationV2{
		UnchangedV2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OperationV2) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DeleteV2
	err = newStrictDecoder(data).Decode(&dst.DeleteV2)
	if err == nil {
		jsonDeleteV2, _ := json.Marshal(dst.DeleteV2)
		if string(jsonDeleteV2) == "{}" { // empty struct
			dst.DeleteV2 = nil
		} else {
			if err = validator.Validate(dst.DeleteV2); err != nil {
				dst.DeleteV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeleteV2 = nil
	}

	// try to unmarshal data into PutV2
	err = newStrictDecoder(data).Decode(&dst.PutV2)
	if err == nil {
		jsonPutV2, _ := json.Marshal(dst.PutV2)
		if string(jsonPutV2) == "{}" { // empty struct
			dst.PutV2 = nil
		} else {
			if err = validator.Validate(dst.PutV2); err != nil {
				dst.PutV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PutV2 = nil
	}

	// try to unmarshal data into UnchangedV2
	err = newStrictDecoder(data).Decode(&dst.UnchangedV2)
	if err == nil {
		jsonUnchangedV2, _ := json.Marshal(dst.UnchangedV2)
		if string(jsonUnchangedV2) == "{}" { // empty struct
			dst.UnchangedV2 = nil
		} else {
			if err = validator.Validate(dst.UnchangedV2); err != nil {
				dst.UnchangedV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.UnchangedV2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeleteV2 = nil
		dst.PutV2 = nil
		dst.UnchangedV2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OperationV2)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OperationV2)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OperationV2) MarshalJSON() ([]byte, error) {
	if src.DeleteV2 != nil {
		return json.Marshal(&src.DeleteV2)
	}

	if src.PutV2 != nil {
		return json.Marshal(&src.PutV2)
	}

	if src.UnchangedV2 != nil {
		return json.Marshal(&src.UnchangedV2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OperationV2) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DeleteV2 != nil {
		return obj.DeleteV2
	}

	if obj.PutV2 != nil {
		return obj.PutV2
	}

	if obj.UnchangedV2 != nil {
		return obj.UnchangedV2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OperationV2) GetActualInstanceValue() (interface{}) {
	if obj.DeleteV2 != nil {
		return *obj.DeleteV2
	}

	if obj.PutV2 != nil {
		return *obj.PutV2
	}

	if obj.UnchangedV2 != nil {
		return *obj.UnchangedV2
	}

	// all schemas are nil
	return nil
}

type NullableOperationV2 struct {
	value *OperationV2
	isSet bool
}

func (v NullableOperationV2) Get() *OperationV2 {
	return v.value
}

func (v *NullableOperationV2) Set(val *OperationV2) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationV2) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationV2(val *OperationV2) *NullableOperationV2 {
	return &NullableOperationV2{value: val, isSet: true}
}

func (v NullableOperationV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


