/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.104.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ReferenceV2 - struct for ReferenceV2
type ReferenceV2 struct {
	BranchV2 *BranchV2
	DetachedV2 *DetachedV2
	TagV2 *TagV2
}

// BranchV2AsReferenceV2 is a convenience function that returns BranchV2 wrapped in ReferenceV2
func BranchV2AsReferenceV2(v *BranchV2) ReferenceV2 {
	return ReferenceV2{
		BranchV2: v,
	}
}

// DetachedV2AsReferenceV2 is a convenience function that returns DetachedV2 wrapped in ReferenceV2
func DetachedV2AsReferenceV2(v *DetachedV2) ReferenceV2 {
	return ReferenceV2{
		DetachedV2: v,
	}
}

// TagV2AsReferenceV2 is a convenience function that returns TagV2 wrapped in ReferenceV2
func TagV2AsReferenceV2(v *TagV2) ReferenceV2 {
	return ReferenceV2{
		TagV2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ReferenceV2) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BranchV2
	err = newStrictDecoder(data).Decode(&dst.BranchV2)
	if err == nil {
		jsonBranchV2, _ := json.Marshal(dst.BranchV2)
		if string(jsonBranchV2) == "{}" { // empty struct
			dst.BranchV2 = nil
		} else {
			if err = validator.Validate(dst.BranchV2); err != nil {
				dst.BranchV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.BranchV2 = nil
	}

	// try to unmarshal data into DetachedV2
	err = newStrictDecoder(data).Decode(&dst.DetachedV2)
	if err == nil {
		jsonDetachedV2, _ := json.Marshal(dst.DetachedV2)
		if string(jsonDetachedV2) == "{}" { // empty struct
			dst.DetachedV2 = nil
		} else {
			if err = validator.Validate(dst.DetachedV2); err != nil {
				dst.DetachedV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DetachedV2 = nil
	}

	// try to unmarshal data into TagV2
	err = newStrictDecoder(data).Decode(&dst.TagV2)
	if err == nil {
		jsonTagV2, _ := json.Marshal(dst.TagV2)
		if string(jsonTagV2) == "{}" { // empty struct
			dst.TagV2 = nil
		} else {
			if err = validator.Validate(dst.TagV2); err != nil {
				dst.TagV2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TagV2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BranchV2 = nil
		dst.DetachedV2 = nil
		dst.TagV2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ReferenceV2)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ReferenceV2)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ReferenceV2) MarshalJSON() ([]byte, error) {
	if src.BranchV2 != nil {
		return json.Marshal(&src.BranchV2)
	}

	if src.DetachedV2 != nil {
		return json.Marshal(&src.DetachedV2)
	}

	if src.TagV2 != nil {
		return json.Marshal(&src.TagV2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ReferenceV2) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BranchV2 != nil {
		return obj.BranchV2
	}

	if obj.DetachedV2 != nil {
		return obj.DetachedV2
	}

	if obj.TagV2 != nil {
		return obj.TagV2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ReferenceV2) GetActualInstanceValue() (interface{}) {
	if obj.BranchV2 != nil {
		return *obj.BranchV2
	}

	if obj.DetachedV2 != nil {
		return *obj.DetachedV2
	}

	if obj.TagV2 != nil {
		return *obj.TagV2
	}

	// all schemas are nil
	return nil
}

type NullableReferenceV2 struct {
	value *ReferenceV2
	isSet bool
}

func (v NullableReferenceV2) Get() *ReferenceV2 {
	return v.value
}

func (v *NullableReferenceV2) Set(val *ReferenceV2) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceV2) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceV2(val *ReferenceV2) *NullableReferenceV2 {
	return &NullableReferenceV2{value: val, isSet: true}
}

func (v NullableReferenceV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


