/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.104.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OperationV1 - Describes an operation to be performed against one content object.  The Nessie backend will validate the correctness of the operations.
type OperationV1 struct {
	DeleteV1 *DeleteV1
	PutV1 *PutV1
	UnchangedV1 *UnchangedV1
}

// DeleteV1AsOperationV1 is a convenience function that returns DeleteV1 wrapped in OperationV1
func DeleteV1AsOperationV1(v *DeleteV1) OperationV1 {
	return OperationV1{
		DeleteV1: v,
	}
}

// PutV1AsOperationV1 is a convenience function that returns PutV1 wrapped in OperationV1
func PutV1AsOperationV1(v *PutV1) OperationV1 {
	return OperationV1{
		PutV1: v,
	}
}

// UnchangedV1AsOperationV1 is a convenience function that returns UnchangedV1 wrapped in OperationV1
func UnchangedV1AsOperationV1(v *UnchangedV1) OperationV1 {
	return OperationV1{
		UnchangedV1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OperationV1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DeleteV1
	err = newStrictDecoder(data).Decode(&dst.DeleteV1)
	if err == nil {
		jsonDeleteV1, _ := json.Marshal(dst.DeleteV1)
		if string(jsonDeleteV1) == "{}" { // empty struct
			dst.DeleteV1 = nil
		} else {
			if err = validator.Validate(dst.DeleteV1); err != nil {
				dst.DeleteV1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeleteV1 = nil
	}

	// try to unmarshal data into PutV1
	err = newStrictDecoder(data).Decode(&dst.PutV1)
	if err == nil {
		jsonPutV1, _ := json.Marshal(dst.PutV1)
		if string(jsonPutV1) == "{}" { // empty struct
			dst.PutV1 = nil
		} else {
			if err = validator.Validate(dst.PutV1); err != nil {
				dst.PutV1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PutV1 = nil
	}

	// try to unmarshal data into UnchangedV1
	err = newStrictDecoder(data).Decode(&dst.UnchangedV1)
	if err == nil {
		jsonUnchangedV1, _ := json.Marshal(dst.UnchangedV1)
		if string(jsonUnchangedV1) == "{}" { // empty struct
			dst.UnchangedV1 = nil
		} else {
			if err = validator.Validate(dst.UnchangedV1); err != nil {
				dst.UnchangedV1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.UnchangedV1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeleteV1 = nil
		dst.PutV1 = nil
		dst.UnchangedV1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OperationV1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OperationV1)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OperationV1) MarshalJSON() ([]byte, error) {
	if src.DeleteV1 != nil {
		return json.Marshal(&src.DeleteV1)
	}

	if src.PutV1 != nil {
		return json.Marshal(&src.PutV1)
	}

	if src.UnchangedV1 != nil {
		return json.Marshal(&src.UnchangedV1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OperationV1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DeleteV1 != nil {
		return obj.DeleteV1
	}

	if obj.PutV1 != nil {
		return obj.PutV1
	}

	if obj.UnchangedV1 != nil {
		return obj.UnchangedV1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OperationV1) GetActualInstanceValue() (interface{}) {
	if obj.DeleteV1 != nil {
		return *obj.DeleteV1
	}

	if obj.PutV1 != nil {
		return *obj.PutV1
	}

	if obj.UnchangedV1 != nil {
		return *obj.UnchangedV1
	}

	// all schemas are nil
	return nil
}

type NullableOperationV1 struct {
	value *OperationV1
	isSet bool
}

func (v NullableOperationV1) Get() *OperationV1 {
	return v.value
}

func (v *NullableOperationV1) Set(val *OperationV1) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationV1) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationV1(val *OperationV1) *NullableOperationV1 {
	return &NullableOperationV1{value: val, isSet: true}
}

func (v NullableOperationV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


