/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.104.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ReferenceV1 - struct for ReferenceV1
type ReferenceV1 struct {
	BranchV1 *BranchV1
	DetachedV1 *DetachedV1
	TagV1 *TagV1
}

// BranchV1AsReferenceV1 is a convenience function that returns BranchV1 wrapped in ReferenceV1
func BranchV1AsReferenceV1(v *BranchV1) ReferenceV1 {
	return ReferenceV1{
		BranchV1: v,
	}
}

// DetachedV1AsReferenceV1 is a convenience function that returns DetachedV1 wrapped in ReferenceV1
func DetachedV1AsReferenceV1(v *DetachedV1) ReferenceV1 {
	return ReferenceV1{
		DetachedV1: v,
	}
}

// TagV1AsReferenceV1 is a convenience function that returns TagV1 wrapped in ReferenceV1
func TagV1AsReferenceV1(v *TagV1) ReferenceV1 {
	return ReferenceV1{
		TagV1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ReferenceV1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BranchV1
	err = newStrictDecoder(data).Decode(&dst.BranchV1)
	if err == nil {
		jsonBranchV1, _ := json.Marshal(dst.BranchV1)
		if string(jsonBranchV1) == "{}" { // empty struct
			dst.BranchV1 = nil
		} else {
			if err = validator.Validate(dst.BranchV1); err != nil {
				dst.BranchV1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.BranchV1 = nil
	}

	// try to unmarshal data into DetachedV1
	err = newStrictDecoder(data).Decode(&dst.DetachedV1)
	if err == nil {
		jsonDetachedV1, _ := json.Marshal(dst.DetachedV1)
		if string(jsonDetachedV1) == "{}" { // empty struct
			dst.DetachedV1 = nil
		} else {
			if err = validator.Validate(dst.DetachedV1); err != nil {
				dst.DetachedV1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.DetachedV1 = nil
	}

	// try to unmarshal data into TagV1
	err = newStrictDecoder(data).Decode(&dst.TagV1)
	if err == nil {
		jsonTagV1, _ := json.Marshal(dst.TagV1)
		if string(jsonTagV1) == "{}" { // empty struct
			dst.TagV1 = nil
		} else {
			if err = validator.Validate(dst.TagV1); err != nil {
				dst.TagV1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TagV1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BranchV1 = nil
		dst.DetachedV1 = nil
		dst.TagV1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ReferenceV1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ReferenceV1)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ReferenceV1) MarshalJSON() ([]byte, error) {
	if src.BranchV1 != nil {
		return json.Marshal(&src.BranchV1)
	}

	if src.DetachedV1 != nil {
		return json.Marshal(&src.DetachedV1)
	}

	if src.TagV1 != nil {
		return json.Marshal(&src.TagV1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ReferenceV1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BranchV1 != nil {
		return obj.BranchV1
	}

	if obj.DetachedV1 != nil {
		return obj.DetachedV1
	}

	if obj.TagV1 != nil {
		return obj.TagV1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ReferenceV1) GetActualInstanceValue() (interface{}) {
	if obj.BranchV1 != nil {
		return *obj.BranchV1
	}

	if obj.DetachedV1 != nil {
		return *obj.DetachedV1
	}

	if obj.TagV1 != nil {
		return *obj.TagV1
	}

	// all schemas are nil
	return nil
}

type NullableReferenceV1 struct {
	value *ReferenceV1
	isSet bool
}

func (v NullableReferenceV1) Get() *ReferenceV1 {
	return v.value
}

func (v *NullableReferenceV1) Set(val *ReferenceV1) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceV1) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceV1(val *ReferenceV1) *NullableReferenceV1 {
	return &NullableReferenceV1{value: val, isSet: true}
}

func (v NullableReferenceV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


