/*
Nessie API

Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables

API version: 0.104.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Reference - struct for Reference
type Reference struct {
	Branch *Branch
	Detached *Detached
	Tag *Tag
}

// BranchAsReference is a convenience function that returns Branch wrapped in Reference
func BranchAsReference(v *Branch) Reference {
	return Reference{
		Branch: v,
	}
}

// DetachedAsReference is a convenience function that returns Detached wrapped in Reference
func DetachedAsReference(v *Detached) Reference {
	return Reference{
		Detached: v,
	}
}

// TagAsReference is a convenience function that returns Tag wrapped in Reference
func TagAsReference(v *Tag) Reference {
	return Reference{
		Tag: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Reference) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Branch
	err = newStrictDecoder(data).Decode(&dst.Branch)
	if err == nil {
		jsonBranch, _ := json.Marshal(dst.Branch)
		if string(jsonBranch) == "{}" { // empty struct
			dst.Branch = nil
		} else {
			if err = validator.Validate(dst.Branch); err != nil {
				dst.Branch = nil
			} else {
				match++
			}
		}
	} else {
		dst.Branch = nil
	}

	// try to unmarshal data into Detached
	err = newStrictDecoder(data).Decode(&dst.Detached)
	if err == nil {
		jsonDetached, _ := json.Marshal(dst.Detached)
		if string(jsonDetached) == "{}" { // empty struct
			dst.Detached = nil
		} else {
			if err = validator.Validate(dst.Detached); err != nil {
				dst.Detached = nil
			} else {
				match++
			}
		}
	} else {
		dst.Detached = nil
	}

	// try to unmarshal data into Tag
	err = newStrictDecoder(data).Decode(&dst.Tag)
	if err == nil {
		jsonTag, _ := json.Marshal(dst.Tag)
		if string(jsonTag) == "{}" { // empty struct
			dst.Tag = nil
		} else {
			if err = validator.Validate(dst.Tag); err != nil {
				dst.Tag = nil
			} else {
				match++
			}
		}
	} else {
		dst.Tag = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Branch = nil
		dst.Detached = nil
		dst.Tag = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Reference)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Reference)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Reference) MarshalJSON() ([]byte, error) {
	if src.Branch != nil {
		return json.Marshal(&src.Branch)
	}

	if src.Detached != nil {
		return json.Marshal(&src.Detached)
	}

	if src.Tag != nil {
		return json.Marshal(&src.Tag)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Reference) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Branch != nil {
		return obj.Branch
	}

	if obj.Detached != nil {
		return obj.Detached
	}

	if obj.Tag != nil {
		return obj.Tag
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Reference) GetActualInstanceValue() (interface{}) {
	if obj.Branch != nil {
		return *obj.Branch
	}

	if obj.Detached != nil {
		return *obj.Detached
	}

	if obj.Tag != nil {
		return *obj.Tag
	}

	// all schemas are nil
	return nil
}

type NullableReference struct {
	value *Reference
	isSet bool
}

func (v NullableReference) Get() *Reference {
	return v.value
}

func (v *NullableReference) Set(val *Reference) {
	v.value = val
	v.isSet = true
}

func (v NullableReference) IsSet() bool {
	return v.isSet
}

func (v *NullableReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReference(val *Reference) *NullableReference {
	return &NullableReference{value: val, isSet: true}
}

func (v NullableReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


