//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthConfig) DeepCopyInto(out *BasicAuthConfig) {
	*out = *in
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthConfig.
func (in *BasicAuthConfig) DeepCopy() *BasicAuthConfig {
	if in == nil {
		return nil
	}
	out := new(BasicAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CamelCaseTransformation) DeepCopyInto(out *CamelCaseTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CamelCaseTransformation.
func (in *CamelCaseTransformation) DeepCopy() *CamelCaseTransformation {
	if in == nil {
		return nil
	}
	out := new(CamelCaseTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlow) DeepCopyInto(out *DataFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlow.
func (in *DataFlow) DeepCopy() *DataFlow {
	if in == nil {
		return nil
	}
	out := new(DataFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowList) DeepCopyInto(out *DataFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowList.
func (in *DataFlowList) DeepCopy() *DataFlowList {
	if in == nil {
		return nil
	}
	out := new(DataFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowSpec) DeepCopyInto(out *DataFlowSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Sink.DeepCopyInto(&out.Sink)
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]TransformationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowSpec.
func (in *DataFlowSpec) DeepCopy() *DataFlowSpec {
	if in == nil {
		return nil
	}
	out := new(DataFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowStatus) DeepCopyInto(out *DataFlowStatus) {
	*out = *in
	if in.LastProcessedTime != nil {
		in, out := &in.LastProcessedTime, &out.LastProcessedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowStatus.
func (in *DataFlowStatus) DeepCopy() *DataFlowStatus {
	if in == nil {
		return nil
	}
	out := new(DataFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterTransformation) DeepCopyInto(out *FilterTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterTransformation.
func (in *FilterTransformation) DeepCopy() *FilterTransformation {
	if in == nil {
		return nil
	}
	out := new(FilterTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlattenTransformation) DeepCopyInto(out *FlattenTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlattenTransformation.
func (in *FlattenTransformation) DeepCopy() *FlattenTransformation {
	if in == nil {
		return nil
	}
	out := new(FlattenTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergSinkSpec) DeepCopyInto(out *IcebergSinkSpec) {
	*out = *in
	if in.AutoCreateNamespace != nil {
		in, out := &in.AutoCreateNamespace, &out.AutoCreateNamespace
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.RESTCatalogURLSecretRef != nil {
		in, out := &in.RESTCatalogURLSecretRef, &out.RESTCatalogURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSRegionSecretRef != nil {
		in, out := &in.AWSRegionSecretRef, &out.AWSRegionSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSAccessKeyIDSecretRef != nil {
		in, out := &in.AWSAccessKeyIDSecretRef, &out.AWSAccessKeyIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSSecretAccessKeySecretRef != nil {
		in, out := &in.AWSSecretAccessKeySecretRef, &out.AWSSecretAccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSEndpointURLSecretRef != nil {
		in, out := &in.AWSEndpointURLSecretRef, &out.AWSEndpointURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergSinkSpec.
func (in *IcebergSinkSpec) DeepCopy() *IcebergSinkSpec {
	if in == nil {
		return nil
	}
	out := new(IcebergSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergSourceSpec) DeepCopyInto(out *IcebergSourceSpec) {
	*out = *in
	if in.RESTCatalogURLSecretRef != nil {
		in, out := &in.RESTCatalogURLSecretRef, &out.RESTCatalogURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSRegionSecretRef != nil {
		in, out := &in.AWSRegionSecretRef, &out.AWSRegionSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSAccessKeyIDSecretRef != nil {
		in, out := &in.AWSAccessKeyIDSecretRef, &out.AWSAccessKeyIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSSecretAccessKeySecretRef != nil {
		in, out := &in.AWSSecretAccessKeySecretRef, &out.AWSSecretAccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSEndpointURLSecretRef != nil {
		in, out := &in.AWSEndpointURLSecretRef, &out.AWSEndpointURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergSourceSpec.
func (in *IcebergSourceSpec) DeepCopy() *IcebergSourceSpec {
	if in == nil {
		return nil
	}
	out := new(IcebergSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSinkSpec) DeepCopyInto(out *KafkaSinkSpec) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SASL != nil {
		in, out := &in.SASL, &out.SASL
		*out = new(SASLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BrokersSecretRef != nil {
		in, out := &in.BrokersSecretRef, &out.BrokersSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TopicSecretRef != nil {
		in, out := &in.TopicSecretRef, &out.TopicSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSinkSpec.
func (in *KafkaSinkSpec) DeepCopy() *KafkaSinkSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceSpec) DeepCopyInto(out *KafkaSourceSpec) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SASL != nil {
		in, out := &in.SASL, &out.SASL
		*out = new(SASLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BrokersSecretRef != nil {
		in, out := &in.BrokersSecretRef, &out.BrokersSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TopicSecretRef != nil {
		in, out := &in.TopicSecretRef, &out.TopicSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ConsumerGroupSecretRef != nil {
		in, out := &in.ConsumerGroupSecretRef, &out.ConsumerGroupSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AvroSchemaSecretRef != nil {
		in, out := &in.AvroSchemaSecretRef, &out.AvroSchemaSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SchemaRegistry != nil {
		in, out := &in.SchemaRegistry, &out.SchemaRegistry
		*out = new(SchemaRegistryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceSpec.
func (in *KafkaSourceSpec) DeepCopy() *KafkaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskTransformation) DeepCopyInto(out *MaskTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskTransformation.
func (in *MaskTransformation) DeepCopy() *MaskTransformation {
	if in == nil {
		return nil
	}
	out := new(MaskTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NessieSinkSpec) DeepCopyInto(out *NessieSinkSpec) {
	*out = *in
	if in.AutoCreateNamespace != nil {
		in, out := &in.AutoCreateNamespace, &out.AutoCreateNamespace
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.NessieURLSecretRef != nil {
		in, out := &in.NessieURLSecretRef, &out.NessieURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.BranchSecretRef != nil {
		in, out := &in.BranchSecretRef, &out.BranchSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSRegionSecretRef != nil {
		in, out := &in.AWSRegionSecretRef, &out.AWSRegionSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSAccessKeyIDSecretRef != nil {
		in, out := &in.AWSAccessKeyIDSecretRef, &out.AWSAccessKeyIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSSecretAccessKeySecretRef != nil {
		in, out := &in.AWSSecretAccessKeySecretRef, &out.AWSSecretAccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSEndpointURLSecretRef != nil {
		in, out := &in.AWSEndpointURLSecretRef, &out.AWSEndpointURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NessieSinkSpec.
func (in *NessieSinkSpec) DeepCopy() *NessieSinkSpec {
	if in == nil {
		return nil
	}
	out := new(NessieSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NessieSourceSpec) DeepCopyInto(out *NessieSourceSpec) {
	*out = *in
	if in.NessieURLSecretRef != nil {
		in, out := &in.NessieURLSecretRef, &out.NessieURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.BranchSecretRef != nil {
		in, out := &in.BranchSecretRef, &out.BranchSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSRegionSecretRef != nil {
		in, out := &in.AWSRegionSecretRef, &out.AWSRegionSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSAccessKeyIDSecretRef != nil {
		in, out := &in.AWSAccessKeyIDSecretRef, &out.AWSAccessKeyIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSSecretAccessKeySecretRef != nil {
		in, out := &in.AWSSecretAccessKeySecretRef, &out.AWSSecretAccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AWSEndpointURLSecretRef != nil {
		in, out := &in.AWSEndpointURLSecretRef, &out.AWSEndpointURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NessieSourceSpec.
func (in *NessieSourceSpec) DeepCopy() *NessieSourceSpec {
	if in == nil {
		return nil
	}
	out := new(NessieSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSinkSpec) DeepCopyInto(out *PostgreSQLSinkSpec) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSinkSpec.
func (in *PostgreSQLSinkSpec) DeepCopy() *PostgreSQLSinkSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSourceSpec) DeepCopyInto(out *PostgreSQLSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(int32)
		**out = **in
	}
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSourceSpec.
func (in *PostgreSQLSourceSpec) DeepCopy() *PostgreSQLSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveTransformation) DeepCopyInto(out *RemoveTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveTransformation.
func (in *RemoveTransformation) DeepCopy() *RemoveTransformation {
	if in == nil {
		return nil
	}
	out := new(RemoveTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteRule) DeepCopyInto(out *RouteRule) {
	*out = *in
	in.Sink.DeepCopyInto(&out.Sink)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteRule.
func (in *RouteRule) DeepCopy() *RouteRule {
	if in == nil {
		return nil
	}
	out := new(RouteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTransformation) DeepCopyInto(out *RouterTransformation) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTransformation.
func (in *RouterTransformation) DeepCopy() *RouterTransformation {
	if in == nil {
		return nil
	}
	out := new(RouterTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SASLConfig) DeepCopyInto(out *SASLConfig) {
	*out = *in
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SASLConfig.
func (in *SASLConfig) DeepCopy() *SASLConfig {
	if in == nil {
		return nil
	}
	out := new(SASLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaRegistryConfig) DeepCopyInto(out *SchemaRegistryConfig) {
	*out = *in
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaRegistryConfig.
func (in *SchemaRegistryConfig) DeepCopy() *SchemaRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(SchemaRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectTransformation) DeepCopyInto(out *SelectTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectTransformation.
func (in *SelectTransformation) DeepCopy() *SelectTransformation {
	if in == nil {
		return nil
	}
	out := new(SelectTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkSpec) DeepCopyInto(out *SinkSpec) {
	*out = *in
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaSinkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLSinkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Iceberg != nil {
		in, out := &in.Iceberg, &out.Iceberg
		*out = new(IcebergSinkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Nessie != nil {
		in, out := &in.Nessie, &out.Nessie
		*out = new(NessieSinkSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkSpec.
func (in *SinkSpec) DeepCopy() *SinkSpec {
	if in == nil {
		return nil
	}
	out := new(SinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnakeCaseTransformation) DeepCopyInto(out *SnakeCaseTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnakeCaseTransformation.
func (in *SnakeCaseTransformation) DeepCopy() *SnakeCaseTransformation {
	if in == nil {
		return nil
	}
	out := new(SnakeCaseTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Iceberg != nil {
		in, out := &in.Iceberg, &out.Iceberg
		*out = new(IcebergSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Nessie != nil {
		in, out := &in.Nessie, &out.Nessie
		*out = new(NessieSourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CertSecretRef != nil {
		in, out := &in.CertSecretRef, &out.CertSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.KeySecretRef != nil {
		in, out := &in.KeySecretRef, &out.KeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampTransformation) DeepCopyInto(out *TimestampTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampTransformation.
func (in *TimestampTransformation) DeepCopy() *TimestampTransformation {
	if in == nil {
		return nil
	}
	out := new(TimestampTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformationSpec) DeepCopyInto(out *TransformationSpec) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(TimestampTransformation)
		**out = **in
	}
	if in.Flatten != nil {
		in, out := &in.Flatten, &out.Flatten
		*out = new(FlattenTransformation)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(FilterTransformation)
		**out = **in
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = new(MaskTransformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Router != nil {
		in, out := &in.Router, &out.Router
		*out = new(RouterTransformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Select != nil {
		in, out := &in.Select, &out.Select
		*out = new(SelectTransformation)
		(*in).DeepCopyInto(*out)
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = new(RemoveTransformation)
		(*in).DeepCopyInto(*out)
	}
	if in.SnakeCase != nil {
		in, out := &in.SnakeCase, &out.SnakeCase
		*out = new(SnakeCaseTransformation)
		**out = **in
	}
	if in.CamelCase != nil {
		in, out := &in.CamelCase, &out.CamelCase
		*out = new(CamelCaseTransformation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformationSpec.
func (in *TransformationSpec) DeepCopy() *TransformationSpec {
	if in == nil {
		return nil
	}
	out := new(TransformationSpec)
	in.DeepCopyInto(out)
	return out
}
